/* Generated By:JJTree: Do not edit this line. ./JJTDotParserTreeConstants.java */

package ua.gradsoft.parsers.dot.jjt;

public interface JJTDotParserTreeConstants
{
  public int JJTDOTGRAPH = 0;
  public int JJTDOTSTMTLIST = 1;
  public int JJTSTMT = 2;
  public int JJTNODEOREDGESTMT = 3;
  public int JJTSUBGRAPHOREDGESUBGRAPHSTMT = 4;
  public int JJTDOTATTRSTMT = 5;
  public int JJTATTRLIST = 6;
  public int JJTATTRASSIGNMENTSLIST = 7;
  public int JJTDOTATTRIBUTEASSIGNMENT = 8;
  public int JJTDOTNODEID = 9;
  public int JJTPORT = 10;
  public int JJTPORTLOCATION = 11;
  public int JJTPORTANGLE = 12;
  public int JJTEDGESTMTTAIL = 13;
  public int JJTID = 14;
  public int JJTEDGERHS = 15;
  public int JJTEDGEOP = 16;
  public int JJTDOTSUBGRAPH = 17;
  public int JJTDOTCOMPOUNDRECORD = 18;
  public int JJTDOTRECORD = 19;
  public int JJTDOTRECORDELEMENT = 20;
  public int JJTDOTRECORDV = 21;


  public String[] jjtNodeName = {
    "dotGraph",
    "dotStmtList",
    "stmt",
    "nodeOrEdgeStmt",
    "subgraphOrEdgeSubgraphStmt",
    "dotAttrStmt",
    "attrList",
    "attrAssignmentsList",
    "dotAttributeAssignment",
    "dotNodeId",
    "port",
    "portLocation",
    "portAngle",
    "edgeStmtTail",
    "id",
    "edgeRHS",
    "edgeOp",
    "dotSubgraph",
    "dotCompoundRecord",
    "dotRecord",
    "dotRecordElement",
    "dotRecordV",
  };
}
