/* Generated By:JJTree&JavaCC: Do not edit this line. JJTDotParserConstants.java */
package ua.gradsoft.parsers.dot.jjt;

public interface JJTDotParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int GRAPH = 13;
  int DIGRAPH = 14;
  int STRICT = 15;
  int SUBGRAPH = 16;
  int NODE = 17;
  int EDGE = 18;
  int INTEGER_LITERAL = 19;
  int DECIMAL_LITERAL = 20;
  int HEX_LITERAL = 21;
  int OCTAL_LITERAL = 22;
  int FLOATING_POINT_LITERAL = 23;
  int EXPONENT = 24;
  int CHARACTER_LITERAL = 25;
  int STRING_LITERAL = 26;
  int IDENTIFIER = 27;
  int LETTER = 28;
  int DIGIT = 29;
  int LPAREN = 30;
  int RPAREN = 31;
  int LBRACE = 32;
  int RBRACE = 33;
  int LBRACEBRACE = 34;
  int RBRACEBRACE = 35;
  int LBRACKET = 36;
  int RBRACKET = 37;
  int SEMICOLON = 38;
  int COMMA = 39;
  int DOT = 40;
  int AT = 41;
  int EQ = 42;
  int GRAPG_EDGE = 43;
  int DIGRAPG_EDGE = 44;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"graph\"",
    "\"digraph\"",
    "\"strict\"",
    "\"subgraph\"",
    "\"node\"",
    "\"edge\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"{{\"",
    "\"}}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"--\"",
    "\"->\"",
    "\":\"",
    "\"|\"",
  };

}
