/* Generated By:JJTree: Do not edit this line. ./PHPTreeConstants.java */

package ua.gradsoft.parsers.php5.jjt;

public interface PHPTreeConstants
{
  public int JJTPHPPAGE = 0;
  public int JJTHTMLBLOCKS = 1;
  public int JJTHTMLBLOCK = 2;
  public int JJTSTATEMENT = 3;
  public int JJTTHROWSTATEMENT = 4;
  public int JJTTRYBLOCK = 5;
  public int JJTCATCHBLOCKS = 6;
  public int JJTCATCHBLOCK = 7;
  public int JJTENDOFSTATEMENT = 8;
  public int JJTEMBEDDEDHTML = 9;
  public int JJTDEFINESTATEMENT = 10;
  public int JJTLABELEDSTATEMENTS = 11;
  public int JJTSTATEMENTS = 12;
  public int JJTGOTOLABELEDSTATEMENT = 13;
  public int JJTEXPRESSIONSTATEMENT = 14;
  public int JJTCOMPOUNDSTATEMENT = 15;
  public int JJTSELECTIONSTATEMENT = 16;
  public int JJTSELECTIONIFSTATEMENT = 17;
  public int JJTSELECTIONSWITCHSTATEMENT = 18;
  public int JJTCASESTATEMENTS = 19;
  public int JJTSELECTIONELSEIFCLAUSES = 20;
  public int JJTSELECTIONELSEIFCLAUSE = 21;
  public int JJTITERATIONSTATEMENT = 22;
  public int JJTWHILESTATEMENT = 23;
  public int JJTDOSTATEMENT = 24;
  public int JJTFORSTATEMENT = 25;
  public int JJTFOREACHSTATEMENT = 26;
  public int JJTJUMPSTATEMENT = 27;
  public int JJTCONTINUESTATEMENT = 28;
  public int JJTBREAKSTATEMENT = 29;
  public int JJTRETURNSTATEMENT = 30;
  public int JJTGOTOSTATEMENT = 31;
  public int JJTPARAMETERLIST = 32;
  public int JJTPARAMETER = 33;
  public int JJTCLASSDECLARATION = 34;
  public int JJTCLASSMEMBERS = 35;
  public int JJTMEMBERDECLARATION = 36;
  public int JJTMEMBERFUNCTIONDECLARATION = 37;
  public int JJTMEMBERCONSTANTDECLARATION = 38;
  public int JJTMEMBERVARIABLESDECLARATION = 39;
  public int JJTVARIABLEDECLSEQ = 40;
  public int JJTVARIABLEDECL = 41;
  public int JJTMEMBERVARIABLEATTRIBUTES = 42;
  public int JJTMEMBERGLOBALSDECLARATION = 43;
  public int JJTVARLIST = 44;
  public int JJTMEMBERABSTRACTFUNCTIONDECLARATION = 45;
  public int JJTMEMBERFUNCTIONATTRIBUTES = 46;
  public int JJTINTERFACEDECLARATION = 47;
  public int JJTINTERFACEMEMBERS = 48;
  public int JJTINTERFACEMEMBER = 49;
  public int JJTINTERFACEMETHODDECLARATION = 50;
  public int JJTINCLUDESTATEMENT = 51;
  public int JJTECHOSTATEMENT = 52;
  public int JJTNAMESPACESTATEMENT = 53;
  public int JJTQUALIFIEDNAME = 54;
  public int JJTUSESTATEMENT = 55;
  public int JJTUSEPAIRS = 56;
  public int JJTUSEPAIR = 57;
  public int JJTDECLARESTATEMENT = 58;
  public int JJTEXPRESSION = 59;
  public int JJTLOGICALTEXTOREXPRESSION = 60;
  public int JJTLOGICALTEXTXOREXPRESSION = 61;
  public int JJTLOGICALTEXTANDEXPRESSION = 62;
  public int JJTASSIGNMENTEXPRESSION = 63;
  public int JJTASSIGNMENTOPERATOR = 64;
  public int JJTCONDITIONALEXPRESSION = 65;
  public int JJTLOGICAL_OR_EXPRESSION = 66;
  public int JJTLOGICAL_AND_EXPRESSION = 67;
  public int JJTBITWISEOREXPRESSION = 68;
  public int JJTBITWISEXOREXPRESSION = 69;
  public int JJTBITWISEANDEXPRESSION = 70;
  public int JJTEQUALITYEXPRESSION = 71;
  public int JJTRELATIONALEXPRESSION = 72;
  public int JJTSHIFTEXPRESSION = 73;
  public int JJTADDITIVEEXPRESSION = 74;
  public int JJTMULTIPLICATIVEEXPRESSION = 75;
  public int JJTCASTEXPRESSION = 76;
  public int JJTUNARYEXPRESSION = 77;
  public int JJTPREFIXINCDECEXPRESSION = 78;
  public int JJTPOSTFIXINCDECEXPRESSION0 = 79;
  public int JJTINCDECSUFFIX = 80;
  public int JJTINSTANCEOFEXPRESSION = 81;
  public int JJTPOSTFIXEXPRESSION = 82;
  public int JJTPOSTFIXEXPRESSIONMETHODCALLSUFFIX = 83;
  public int JJTPOSTFIXEXPRESSIONMEMBERSELECTORSUFFIX = 84;
  public int JJTPOSTFIXEXPRESSIONSCOPERESOLUTIONSUFFIX = 85;
  public int JJTPOSTFIXEXPRESSIONARRAYINDEXSUFFIX = 86;
  public int JJTPOSTFIXEXPRESSIONCURLYBRACKETSSUFFIX = 87;
  public int JJTPRIMARYEXPRESSION = 88;
  public int JJTINBRACESEXPRESSION = 89;
  public int JJTARRAY = 90;
  public int JJTARRAYKEYORVALUE = 91;
  public int JJTCLASSINSTANTIATION = 92;
  public int JJTALLOCATIONEXPRESSION = 93;
  public int JJTCLONEEXPRESSION = 94;
  public int JJTVARIABLE = 95;
  public int JJTARGUMENTEXPRESSIONLIST = 96;
  public int JJTCONSTANT = 97;
  public int JJTSTRING = 98;
  public int JJTDOUBLESTRINGLITERAL = 99;
  public int JJTVISIBILITY = 100;


  public String[] jjtNodeName = {
    "PhpPage",
    "HtmlBlocks",
    "HtmlBlock",
    "Statement",
    "ThrowStatement",
    "TryBlock",
    "CatchBlocks",
    "CatchBlock",
    "EndOfStatement",
    "EmbeddedHtml",
    "DefineStatement",
    "LabeledStatements",
    "Statements",
    "GotoLabeledStatement",
    "ExpressionStatement",
    "CompoundStatement",
    "SelectionStatement",
    "SelectionIfStatement",
    "SelectionSwitchStatement",
    "CaseStatements",
    "SelectionElseIfClauses",
    "SelectionElseIfClause",
    "IterationStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForEachStatement",
    "JumpStatement",
    "ContinueStatement",
    "BreakStatement",
    "ReturnStatement",
    "GotoStatement",
    "ParameterList",
    "Parameter",
    "ClassDeclaration",
    "ClassMembers",
    "MemberDeclaration",
    "MemberFunctionDeclaration",
    "MemberConstantDeclaration",
    "MemberVariablesDeclaration",
    "VariableDeclSeq",
    "VariableDecl",
    "MemberVariableAttributes",
    "MemberGlobalsDeclaration",
    "VarList",
    "MemberAbstractFunctionDeclaration",
    "MemberFunctionAttributes",
    "InterfaceDeclaration",
    "InterfaceMembers",
    "InterfaceMember",
    "InterfaceMethodDeclaration",
    "IncludeStatement",
    "EchoStatement",
    "NamespaceStatement",
    "QualifiedName",
    "UseStatement",
    "UsePairs",
    "UsePair",
    "DeclareStatement",
    "Expression",
    "LogicalTextOrExpression",
    "LogicalTextXorExpression",
    "LogicalTextAndExpression",
    "AssignmentExpression",
    "AssignmentOperator",
    "ConditionalExpression",
    "Logical_Or_Expression",
    "Logical_And_Expression",
    "BitwiseOrExpression",
    "BitwiseXorExpression",
    "BitwiseAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "CastExpression",
    "UnaryExpression",
    "PrefixIncDecExpression",
    "PostfixIncDecExpression0",
    "IncDecSuffix",
    "InstanceOfExpression",
    "PostfixExpression",
    "PostfixExpressionMethodCallSuffix",
    "PostfixExpressionMemberSelectorSuffix",
    "PostfixExpressionScopeResolutionSuffix",
    "PostfixExpressionArrayIndexSuffix",
    "PostfixExpressionCurlyBracketsSuffix",
    "PrimaryExpression",
    "InBracesExpression",
    "Array",
    "ArrayKeyOrValue",
    "ClassInstantiation",
    "AllocationExpression",
    "CloneExpression",
    "Variable",
    "ArgumentExpressionList",
    "Constant",
    "String",
    "DoubleStringLiteral",
    "Visibility",
  };
}
