/* Generated By:JJTree: Do not edit this line. .\JJTJavaParserTreeConstants.java */

package ua.gradsoft.parsers.java5.jjt;

public interface JJTJavaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTPACKAGEDECLARATION = 1;
  public int JJTIMPORTDECLARATION = 2;
  public int JJTMODIFIERS = 3;
  public int JJTTYPEDECLARATION = 4;
  public int JJTCLASSORINTERFACEDECLARATION = 5;
  public int JJTEXTENDSLIST = 6;
  public int JJTIMPLEMENTSLIST = 7;
  public int JJTENUMDECLARATION = 8;
  public int JJTENUMBODY = 9;
  public int JJTENUMCONSTANT = 10;
  public int JJTTYPEPARAMETERS = 11;
  public int JJTTYPEPARAMETER = 12;
  public int JJTTYPEBOUND = 13;
  public int JJTCLASSORINTERFACEBODY = 14;
  public int JJTCLASSORINTERFACEBODYDECLARATION = 15;
  public int JJTFIELDDECLARATION = 16;
  public int JJTVARIABLEDECLARATOR = 17;
  public int JJTVARIABLEDECLARATORID = 18;
  public int JJTVARIABLEINITIALIZER = 19;
  public int JJTARRAYINITIALIZER = 20;
  public int JJTMETHODDECLARATION = 21;
  public int JJTMETHODDECLARATOR = 22;
  public int JJTFORMALPARAMETERS = 23;
  public int JJTFORMALPARAMETER = 24;
  public int JJTCONSTRUCTORDECLARATION = 25;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 26;
  public int JJTEXPLICITTHISCONSTRUCTORINVOCATION = 27;
  public int JJTEXPLICITSUPERCONSTRUCTORINVOCATION = 28;
  public int JJTINITIALIZER = 29;
  public int JJTTYPE = 30;
  public int JJTREFERENCETYPE = 31;
  public int JJTCLASSORINTERFACETYPE = 32;
  public int JJTTYPEARGUMENTS = 33;
  public int JJTTYPEARGUMENT = 34;
  public int JJTWILDCARDBOUNDS = 35;
  public int JJTPRIMITIVETYPE = 36;
  public int JJTRESULTTYPE = 37;
  public int JJTNAME = 38;
  public int JJTNAMELIST = 39;
  public int JJTEXPRESSION = 40;
  public int JJTASSIGNMENTOPERATOR = 41;
  public int JJTCONDITIONALEXPRESSION = 42;
  public int JJTCONDITIONALOREXPRESSION = 43;
  public int JJTCONDITIONALANDEXPRESSION = 44;
  public int JJTINCLUSIVEOREXPRESSION = 45;
  public int JJTEXCLUSIVEOREXPRESSION = 46;
  public int JJTANDEXPRESSION = 47;
  public int JJTEQUALITYEXPRESSION = 48;
  public int JJTEQUALITYEXPRESSIONOPERAND = 49;
  public int JJTINSTANCEOFEXPRESSION = 50;
  public int JJTRELATIONALEXPRESSION = 51;
  public int JJTRELATIONALEXPRESSIONSUFFIX = 52;
  public int JJTSHIFTEXPRESSION = 53;
  public int JJTSHIFTEXPRESSIONOPERAND = 54;
  public int JJTADDITIVEEXPRESSION = 55;
  public int JJTADDITIVEOPERAND = 56;
  public int JJTMULTIPLICATIVEEXPRESSION = 57;
  public int JJTMULTIPLICATIVEOPERAND = 58;
  public int JJTUNARYEXPRESSION = 59;
  public int JJTPREINCREMENTEXPRESSION = 60;
  public int JJTPREDECREMENTEXPRESSION = 61;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 62;
  public int JJTCASTLOOKAHEAD = 63;
  public int JJTPOSTFIXEXPRESSION = 64;
  public int JJTCASTEXPRESSION = 65;
  public int JJTPRIMARYEXPRESSION = 66;
  public int JJTMEMBERSELECTOR = 67;
  public int JJTPRIMARYPREFIX = 68;
  public int JJTPRIMARYSUFFIX = 69;
  public int JJTTHISSELECTOR = 70;
  public int JJTALLOCATIONSELECTOR = 71;
  public int JJTFIELDSELECTOR = 72;
  public int JJTARRAYINDEXSELECTOR = 73;
  public int JJTLITERAL = 74;
  public int JJTINTEGERLITERAL = 75;
  public int JJTCHARACTERLITERAL = 76;
  public int JJTFLOATINGPOINTLITERAL = 77;
  public int JJTSTRINGLITERAL = 78;
  public int JJTBOOLEANLITERAL = 79;
  public int JJTNULLLITERAL = 80;
  public int JJTARGUMENTS = 81;
  public int JJTARGUMENTLIST = 82;
  public int JJTALLOCATIONEXPRESSION = 83;
  public int JJTARRAYDIMSANDINITS = 84;
  public int JJTARRAYDIMS = 85;
  public int JJTARRAYDIM = 86;
  public int JJTSTATEMENT = 87;
  public int JJTSTATEMENTEXPRESSIONSTATEMENT = 88;
  public int JJTASSERTSTATEMENT = 89;
  public int JJTLABELEDSTATEMENT = 90;
  public int JJTBLOCK = 91;
  public int JJTBLOCKSTATEMENT = 92;
  public int JJTLOCALVARIABLEDECLARATION = 93;
  public int JJTEMPTYSTATEMENT = 94;
  public int JJTSTATEMENTEXPRESSION = 95;
  public int JJTSWITCHSTATEMENT = 96;
  public int JJTSWITCHSTATEMENTLABELBLOCK = 97;
  public int JJTSWITCHLABEL = 98;
  public int JJTIFSTATEMENT = 99;
  public int JJTWHILESTATEMENT = 100;
  public int JJTDOSTATEMENT = 101;
  public int JJTFORSTATEMENT = 102;
  public int JJTFOREACHLOOPHEAD = 103;
  public int JJTTRADITIONALFORLOOPHEAD = 104;
  public int JJTFORINIT = 105;
  public int JJTSTATEMENTEXPRESSIONLIST = 106;
  public int JJTFORUPDATE = 107;
  public int JJTBREAKSTATEMENT = 108;
  public int JJTCONTINUESTATEMENT = 109;
  public int JJTRETURNSTATEMENT = 110;
  public int JJTTHROWSTATEMENT = 111;
  public int JJTSYNCHRONIZEDSTATEMENT = 112;
  public int JJTTRYSTATEMENT = 113;
  public int JJTCATCHSEQUENCE = 114;
  public int JJTCATCH = 115;
  public int JJTRUNSIGNEDSHIFT = 116;
  public int JJTRSIGNEDSHIFT = 117;
  public int JJTANNOTATION = 118;
  public int JJTNORMALANNOTATION = 119;
  public int JJTMARKERANNOTATION = 120;
  public int JJTSINGLEMEMBERANNOTATION = 121;
  public int JJTMEMBERVALUEPAIRS = 122;
  public int JJTMEMBERVALUEPAIR = 123;
  public int JJTMEMBERVALUE = 124;
  public int JJTMEMBERVALUEARRAYINITIALIZER = 125;
  public int JJTANNOTATIONTYPEDECLARATION = 126;
  public int JJTANNOTATIONTYPEBODY = 127;
  public int JJTANNOTATIONTYPEMEMBERDECLARATION = 128;
  public int JJTDEFAULTVALUE = 129;
  public int JJTIDENTIFIER = 130;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "PackageDeclaration",
    "ImportDeclaration",
    "Modifiers",
    "TypeDeclaration",
    "ClassOrInterfaceDeclaration",
    "ExtendsList",
    "ImplementsList",
    "EnumDeclaration",
    "EnumBody",
    "EnumConstant",
    "TypeParameters",
    "TypeParameter",
    "TypeBound",
    "ClassOrInterfaceBody",
    "ClassOrInterfaceBodyDeclaration",
    "FieldDeclaration",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "VariableInitializer",
    "ArrayInitializer",
    "MethodDeclaration",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "ExplicitThisConstructorInvocation",
    "ExplicitSuperConstructorInvocation",
    "Initializer",
    "Type",
    "ReferenceType",
    "ClassOrInterfaceType",
    "TypeArguments",
    "TypeArgument",
    "WildcardBounds",
    "PrimitiveType",
    "ResultType",
    "Name",
    "NameList",
    "Expression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "EqualityExpressionOperand",
    "InstanceOfExpression",
    "RelationalExpression",
    "RelationalExpressionSuffix",
    "ShiftExpression",
    "ShiftExpressionOperand",
    "AdditiveExpression",
    "AdditiveOperand",
    "MultiplicativeExpression",
    "MultiplicativeOperand",
    "UnaryExpression",
    "PreIncrementExpression",
    "PreDecrementExpression",
    "UnaryExpressionNotPlusMinus",
    "CastLookahead",
    "PostfixExpression",
    "CastExpression",
    "PrimaryExpression",
    "MemberSelector",
    "PrimaryPrefix",
    "PrimarySuffix",
    "ThisSelector",
    "AllocationSelector",
    "FieldSelector",
    "ArrayIndexSelector",
    "Literal",
    "IntegerLiteral",
    "CharacterLiteral",
    "FloatingPointLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "ArrayDimsAndInits",
    "ArrayDims",
    "ArrayDim",
    "Statement",
    "StatementExpressionStatement",
    "AssertStatement",
    "LabeledStatement",
    "Block",
    "BlockStatement",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchStatementLabelBlock",
    "SwitchLabel",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForEachLoopHead",
    "TraditionalForLoopHead",
    "ForInit",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "SynchronizedStatement",
    "TryStatement",
    "CatchSequence",
    "Catch",
    "RUNSIGNEDSHIFT",
    "RSIGNEDSHIFT",
    "Annotation",
    "NormalAnnotation",
    "MarkerAnnotation",
    "SingleMemberAnnotation",
    "MemberValuePairs",
    "MemberValuePair",
    "MemberValue",
    "MemberValueArrayInitializer",
    "AnnotationTypeDeclaration",
    "AnnotationTypeBody",
    "AnnotationTypeMemberDeclaration",
    "DefaultValue",
    "Identifier",
  };
}
