/* Generated By:JJTree: Do not edit this line. ./JJTDotParsetTreeConstants.java */

package ua.gradsoft.parsers.dot.jjt;

public interface JJTDotParsetTreeConstants
{
  public int JJTDOTGRAPH = 0;
  public int JJTDOTSTMTLIST = 1;
  public int JJTSTMT = 2;
  public int JJTATTRSTMT = 3;
  public int JJTATTRLIST = 4;
  public int JJTATTRASSIGMENTSLIST = 5;
  public int JJTATTRASSIGMENT = 6;
  public int JJTNODESTMT = 7;
  public int JJTNODEID = 8;
  public int JJTPORT = 9;
  public int JJTPORTLOCATION = 10;
  public int JJTPORTANGLE = 11;
  public int JJTEDGESTMT = 12;
  public int JJTID = 13;
  public int JJTEDGERHS = 14;
  public int JJTEDGEOP = 15;
  public int JJTSUBGRAPH = 16;


  public String[] jjtNodeName = {
    "dotGraph",
    "dotStmtList",
    "stmt",
    "attrStmt",
    "attrList",
    "attrAssigmentsList",
    "attrAssigment",
    "nodeStmt",
    "nodeId",
    "port",
    "portLocation",
    "portAngle",
    "edgeStmt",
    "id",
    "edgeRHS",
    "edgeOp",
    "subgraph",
  };
}
